version: "3.8"
services:
  redis:
    image: redis
    ports:
      - "6379:6379"

  web:
    build: .
    image: humtemp:latest
    ports:
      - "8000:8000"
    environment:
      HUMTEMP_REDIS_HOST: redis
      HUMTEMP_BUCKET_OFFSET: "1970-01-01T00:00:00+00:00"
      HUMTEMP_BUCKET_DURATION: "86400"
      HUMTEMP_BUCKET_RETENTION: 5
