version: "3.8"
services:
  redis:
    image: redis
    ports:
      - "6379:6379"

  web:
    build: .
    image: humtemp:latest
    ports:
      - "8000:8000"
    environment:
      HUMTEMP_REDIS_HOST: redis
